# default:
# 	rm -f heads.mli
# 	ocamlopt heads.ml
# 	ocamlopt heads.cmx driver.ml
# 	./a.out

# default:
# 	rm -f uniform.mli
# 	ocamlopt uniform.ml
# 	ocamlopt uniform.cmx driver.ml
# 	./a.out

default:
	rm -f gp.mli
	ocamlopt gp.ml
	ocamlopt gp.cmx driver.ml
	./a.out
